name: "Prepare dart"
description: "Sets up the flutter container for pulling from private repos"

inputs:
  ssh_key:
    description: "SSH key to pull private dependencies"
    required: false

runs:
  using: composite
  steps:
    - name: Enable pulling private dependencies
      if: ${{inputs.ssh_key}}
      run: |
        mkdir -p -m 0700 ~/.ssh/ && touch ~/.ssh/known_hosts
        curl --silent https://api.github.com/meta  | jq --raw-output '"github.com "+.ssh_keys[]' > ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
        mkdir -p -m 0700 /root/.ssh/ && touch /root/.ssh/known_hosts
        curl --silent https://api.github.com/meta  | jq --raw-output '"github.com "+.ssh_keys[]' > /root/.ssh/known_hosts
        chmod 600 /root/.ssh/known_hosts
        eval `ssh-agent -s`
        echo "SSH_AUTH_SOCK=${SSH_AUTH_SOCK}" >> "$GITHUB_ENV"
        (ssh-add  -vvv - <<< "${{ inputs.ssh_key }}") || true
        # Fixup the permissions after the checkout action
        # see https://github.com/actions/checkout/issues/766 and https://github.com/actions/checkout/issues/363
        chown -R $(whoami) .
        flutter --disable-telemetry
      shell: bash
