variables:
  DEPENDABOT_IMAGE: docker.io/andrcuns/dependabot-gitlab:0.31.1

.dependabot-gitlab:
  image:
    name: $DEPENDABOT_IMAGE
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
    RAILS_ENV: production
    SECRET_KEY_BASE: "$SECRET_BASE_KEY"
    PACKAGE_MANAGER: $CI_JOB_NAME
    SETTINGS__GITLAB_URL: $CI_SERVER_URL
    SETTINGS__STANDALONE: "true"
    SETTINGS__LOG_COLOR: "true"
  script:
    - sudo apt-get update && sudo apt-get -y upgrade
    - cd /home/dependabot/app
    - git clone https://github.com/flutter/flutter.git -b stable
    - export PATH="`pwd`/flutter/bin:$PATH"
    - which flutter
    - ./flutter/bin/flutter --version
    - bundle exec rake "dependabot:update[$PROJECT_PATH,$PACKAGE_MANAGER,$DIRECTORY]"


pub:
  extends: .dependabot-gitlab
  rules:
    - if: $DEPENDENCY_UPDATES_DISABLED
      when: never
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $PACKAGE_MANAGER_SET =~ /\bpub\b/'
