name: "Prepare flutter and ssh"
description: "Sets up the flutter container and ssh keys for pulling from private repos"

inputs:
  ssh_key:
    description: "SSH key to pull private dependencies."
    required: true
  flutter_version:
    description: "Flutter version"
    type: string
    required: true

runs:
  using: composite
  steps:
    - name: Enable pulling private dependencies
      shell: bash
      run: |
          mkdir -p ~/.ssh
          echo "${{inputs.ssh_key}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent)
          ssh-add ~/.ssh/id_rsa
          # Fixup the permissions after the checkout action
          # see https://github.com/actions/checkout/issues/766 and https://github.com/actions/checkout/issues/363
          chown -R $(whoami) .
    - name: Setup flutter
      uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
      with:
        flutter-version: ${{ inputs.flutter_version }}
        cache: true
    - run: |
        [ "${{ inputs.flutter_version }}" -ge "3.16.0" ] && flutter --disable-analytics; dart --disable-analytics || flutter --disable-telemetry; dart --disable-telemetry
      shell: bash