name: "General checks like for commit messages. etc"

on:
  workflow_call:

jobs:
  conventional_commits:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' && github.event.pull_request
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check conventional commits
        run: |
          echo "Checking commit messages..."
          COMMIT_MSGS=$(git log --no-merges --format=%s origin/main..HEAD)
          for msg in "${COMMIT_MSGS[@]}"; do
            echo "Checking: $msg"
            if [[ ! $msg =~ ^(ci|feat|fix|docs|style|refactor|perf|test|chore|build|revert)(\(.+\))?:\ .+ ]]; then
              echo "error: invalid commit message: $msg"
              exit 1
            fi
          done
